### ISSUE TITLE
While loading the website on mobile, the particles in the background are stretched out.

### ISSUE THREAD

**Issue by TanushN** [matteobruni/tsparticles#560]
**Describe the bug**

When you initially load the website on mobile or chrome dev (phone dimensions), the particles are stretched out and eventually return back to normal after you scroll down or engage with the page. I think this a problem where the canvas is not taking full height when the website is initially loaded. 

Website Im taking about: [https://tanush.dev](https://tanush.dev)

**To Reproduce**
1. Go to [tanush.dev](https://tanush.dev) on mobile
2. or go to chrome dev and choose a phone dimension, you may have to reload the website again, after you change the 
   dimensions.

**Expected behavior**
The particles should be normal and not stretched out

**Screenshots**
What it should be like:

![image](https://user-images.githubusercontent.com/48323276/87216071-b8bd0380-c301-11ea-997e-e929b158117e.png)

how it looks on mobile dimensions:

![image](https://user-images.githubusercontent.com/48323276/87216095-e30ec100-c301-11ea-8ac8-c93679057768.png)

Usually these stretched particles become normal when a user engages with the website on an actual mobile.

**Desktop (please complete the following information):**
any desktop or browser

**Smartphone (please complete the following information):**
any desktop or browser on IOS and Android

**Comment by matteobruni** [comment]
Hi @TanushN, which version are you using? This bug I think is already fixed in latest version but I could be wrong

**Comment by TanushN** [comment]
@matteobruni Im on the react-particles-js latest version 3.2.1

more info:

```
react-particles-js@3.2.1 | MIT | deps: 2 | versions: 41
Reactified particles.js
https://github.com/Wufe/react-particles-js#readme

dist
.tarball: https://registry.npmjs.org/react-particles-js/-/react-particles-js-3.2.1.tgz
.shasum: a331e80519c9e70f448090915def088f72ed6ed3
.integrity: sha512-sZ6jmwbbHQOtqsChlI7X9iee+iN4C1g9BLch2f9Ck9dvJmAaVT8/kQB1gOQLROFKIFIzQyt34gXzrI7ZNwNspQ==
.unpackedSize: 789.5 kB

dependencies:
lodash: ^4.17.11     tsparticles: ^1.13.6 

maintainers:
- wufe <wufe92@gmail.com>

dist-tags:
beta: 3.3.0-beta.1  latest: 3.2.1       

published 2 months ago by wufe <wufe92@gmail.com>
```

**Comment by TanushN** [comment]
@matteobruni ok looks react-particles-js is using the 1.13.6 version of the tsparticles while the newest version is 1.16.3. Is this the problem? How do I make sure the newest version is used?

**Comment by matteobruni** [comment]
Try using `react-tsparticles`, it uses the same syntax but I maintain it in this project so is updated at every release

**Comment by TanushN** [comment]
@matteobruni I switched to react-tsparticles and I have still have this issue.

**Comment by matteobruni** [comment]
Ok, can you share some code to try reproduce the problem outside your website?

**Comment by TanushN** [comment]
Hi, I put all the code in here: https://github.com/TanushN/portfolio. Here is where the particle code is: https://github.com/TanushN/portfolio/blob/master/src/components/particle.js and here is where it is called in: https://github.com/TanushN/portfolio/blob/master/src/App.js

**Comment by matteobruni** [comment]
Hi @TanushN 
I cloned the repository, I found some issues, I'll describe them here one by one.

---

### `index.html`

I moved the `<style>` tag inner code inside the `App.css`, this fixes the particles issue.

And changed a bit the `#tsparticles` style

```css
#tsparticles {
  width: 100%;
  height: 100%;
  position: fixed;
  top: 0;
  bottom: 0;
  margin: 0;
  padding: 0;
}
```

### `App.js`

The root object in your repo is this:

```jsx
<div
      style={{
        position: "absolute",
        top: 0,
        left: 0,
        width: "100%",
        height: "100%",
      }}
    >
```

but this is enough:

```
<>
```

### `particle.js`

Fixed the import from

```js
import Particles from "react-particles-js";
```

to

```js
import Particles from "react-tsparticles";
```

and removed the div inside the component, leaving only the `<Particles>` tag

### `package.json`

Added the missing dependency

```json
"semantic-ui-css": "^2.4.1"
```

**Comment by TanushN** [comment]
@matteobruni Its fixed now! 👍 Thank you so much for your help and patience! Just to understand, do you know why moving the style tag to app.css fixed the issue?

**Comment by matteobruni** [comment]
I think because React treats inside styles differently, but I'm not 100% sure about it
